### ISSUE TITLE
Script to generate discordant and splitters files from position sorted BAM

### ISSUE THREAD

**Issue by aakrosh** [kunalkathuria/SVXplorer#10]
The users will have position-sorted BAMs in several instances. It might be helpful to provide a python script that takes position sorted BAM and creates a discordant and splitters BAM. Alternatively a bash script that uses SAMtools would be sufficient.

**Comment by kunalkathuria** [comment]
Discordants should include unmapped reads in order to catch de novo INS, unlike currently

**Comment by kunalkathuria** [comment]
We need -F 3074 (this excludes supplementary), not 1294 (this excludes all unmapped and non-primary alignments)
