### ISSUE TITLE
Missing genotype GT in VCF files?

### ISSUE THREAD

**Issue by pauline-ng** [kunalkathuria/SVXplorer#101]
Hi,

Thanks for making SVXplorer. When I look at the output of the VCF file, I notice that the genotype field (10th column, GT) is always "./." . Is there a way to assign it heterozygote (0/1) or homozygote (1/1) genotypes? 

I'm guessing it'd be based on SU, PE, and SR fields.

Thanks,
Pauline

**Comment by kunalkathuria** [comment]
Hi Pauline,

SVXplorer does not have genotyping implemented, but a standard genotyping tool (e.g. svtyper) can update that column if you supply the VCF output from SVXplorer. 

Thank you for using SVXplorer.

Best,

Kunal
