### ISSUE TITLE
CR tag in INFO

### ISSUE THREAD

**Issue by aakrosh** [kunalkathuria/SVXplorer#83]
The CR tag in INFO is described as a string with the following description "Reason for rejection of variant as putative DEL/TD due to corresponding local read depth relative to median of chromosome in question". This tag as it is implemented is not compatible with VCF readers (e.g. pyVCF), which fail  when they attempt to reads this tag. 

A possible solution would be to either write this tag within quotes, so as to signal then ends of the string to the readers, or we could convert this tag into something akin to a categorical variable.

**Comment by kunalkathuria** [comment]
Resolved by 661181f
