### ISSUE TITLE
Using variable 'prevTID' before assignment

### ISSUE THREAD

**Issue by aakrosh** [kunalkathuria/SVXplorer#89]
covPUFilter.py:50. The variable prevTID is used before assignment.

**Comment by kunalkathuria** [comment]
This is a deliberate failsafe, as the second condition should never be reached unless the first is true, which it should never be in the first iteration. The 2 conditions are written to go together.  Acceptable coding practice?

**Comment by aakrosh** [comment]
Having any variable uninitialized is never a good practice. Initialize it, and then add an assert to check that your assumption. Something that follows the pattern below is better.
```
    prev_stop = -1
    prevTID = None
    for k,line in enumerate(fo):
        ...
        if prev_stop == -1: assert prevTID is None
        if prev_stop != -1 and currentTID == prevTID:
            if 0 < start - prev_stop <= RDL:
                chrHash[currentTID][prev_stop:start] = 1

        chrHash[currentTID][start:stop] = 1
        prev_start = start
        prev_stop = stop
        prevTID = currentTID
```
