### ISSUE TITLE
Find variant in a cohort

### ISSUE THREAD

**Issue by ghost** [kunalkathuria/SVXplorer#92]
Hello,

let's say I have several sample, and I want to find SV that are private (unique) to each sample. Is there a preferred way to achieve this with SVXplorer, besides performing each vcf pairwise comparison? 

Thank you

**Comment by kunalkathuria** [comment]
SVXplorer does not support multisample analysis currently, sorry. The best way to do this may be to run SVXplorer on each sample and concatenate/compare the respective variants.bedpe files (in work_dir/results) using, for example, bedtools pairtopair and command-line utilities like grep.

**Comment by ghost** [comment]
Ok thanks! 
Are the outputs of SVXplorere standardized/ normalized already?

**Comment by aakrosh** [comment]
The output of SVXplorer is not normalized. I am assuming you mean parsimonious and left aligned, the same as what you would do for SNPs? We do not test for either, and it would be only possible for variants where the exact breakpoints are known. Or am I misunderstanding you?

Thanks.

**Comment by ghost** [comment]
You understood correctly. I am just trying to find a way of finding common variants between 2 vcf files I realize that might just be impossible as the determination of exact breakpoints coordinates is not something trivial, I would expect that the apparent coordinate of the same breakpoint can vary between samples.

**Comment by aakrosh** [comment]
Understood. As a first pass, you could take the BEDPE output from SVXplorer, and use 'bedtools pairtopair' with a slop to compare the two.

**Comment by ghost** [comment]
yes I am gonna try that. The thing is I have an ancestral population and 10 descendants (I did not make my life easy when I chose my research topic X) ). Structural variant calling is somewhat nightmarish when compared to "simple" SNP calling.
