### ISSUE TITLE
Memory needed to run?

### ISSUE THREAD

**Issue by Solyris83** [kunalkathuria/SVXplorer#95]
Hi, I have been trying to run SVXplorer a few times already and it keeps getting "Killed" on an ec2 instance with 4 core and 32GB ram. May I know what is the recommended hardware needed to run this?

**Comment by kunalkathuria** [comment]
Hi,

SVXplorer runs on 1 core. Table 6 in https://journals.plos.org/ploscompbiol/article/file?id=10.1371/journal.pcbi.1007737&type=printable lists peak memory usage for different data sets. What is the coverage of the data set you are using? Can you evaluate peak memory (https://gist.github.com/netj/526585) and report corresponding entry in the "run.log" file, at the time of peak usage?
