### ISSUE TITLE
Unable to install SVXplorer

### ISSUE THREAD

**Issue by neharajkumar** [kunalkathuria/SVXplorer#97]
Hi,

I am trying to install the tool using **pip2 install -r requirements.txt**

But I get the following error:

Exception:
Traceback (most recent call last):
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pip-1.5.1-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pip-1.5.1-py2.7.egg/pip/commands/install.py", line 258, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pip-1.5.1-py2.7.egg/pip/req.py", line 1572, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pip-1.5.1-py2.7.egg/pip/req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pip-1.5.1-py2.7.egg/pip/req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pip-1.5.1-py2.7.egg/pip/_vendor/pkg_resources.py", line 2612, in parse
    reqs = list(parse_requirements(s))
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pip-1.5.1-py2.7.egg/pip/_vendor/pkg_resources.py", line 2550, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/u/local/apps/python/2.7.3/lib/python2.7/site-packages/pip-1.5.1-py2.7.egg/pip/_vendor/pkg_resources.py", line 2518, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', "python_version < '3'", 'at', " < '3'")

Storing debug log for failure in /u/home/n/neharajk/.pip/pip.log

I have tried using different versions of python (2&3) and neither work. Any help is much appreciated. Thanks!

**Comment by sienkie** [comment]
Could you specify what version of pip2 and setuptools you use?

**Comment by neharajkumar** [comment]
Hi,

For setuptools the version is 50.3.0.post20201006 and python the version is
2.7.3
Thanks!

- Neha Rajkumar

**Comment by sienkie** [comment]
I tested different combinations of setuptools and pip and this error message can appear for older setuptools package versions, which have problem with the first line of the requirements file: `python_version < '3'`. However, older pip versions regardless of setuptools version also throw a similar error. 

@neharajkumar The version you specified seems to be [python 3 specific](https://pypi.org/project/setuptools/50.3.0/#files). If you have multiple python and pip versions, please make sure that you are using an appropriate pip version for your python 2.7.3. Try upgrading your setuptools with: `python -m pip install setuptools --upgrade `,  where `python` is the version of python you would like to use. If this does not help, go ahead and comment the first line of requirements file. As long as you are using the appropriate python version (which for SVXplorer is either 2.7 or 2.6), this will not impact the package. 

@aakrosh please see linked pull request #99

**Comment by neharajkumar** [comment]
I will try this, thank you for your help!

- Neha Rajkumar

**Comment by kunalkathuria** [comment]
Thank you, Karolina! 

@neharajkumar Closing this but please let us know if you encounter any more issues.

**Comment by neharajkumar** [comment]
Hi,

Sorry for the late reply, but I was just able to upgrade setuptools.
However, I am now having another issue with requirements.txt. It seems like
the numpy version specified (numpy-1.20.1) only supports python versions
>3.7. However, I am using python 2.7 since this uses pip2 to install. I
also tried to do pip3 install, which gives me a very long error where it
fails to build wheels for all the packages. One of the errors I was getting
said I needed Cython, so I downloaded that but I am still getting the big
error message. I could send it in a separate email if you want. Any help
would be appreciated.

Thank you!

- Neha Rajkumar

**Comment by sienkie** [comment]
Hi @neharajkumar, if the error massage is to big to paste here, could you forward it to sienkiewicz2k@gmail.com?
